### ISSUE TITLE
Default WPM too fast

### ISSUE THREAD

**Issue by jamestomasino** [jamestomasino/stutter#1]
Change to 400 WPM for new users

**Comment by jamestomasino** [comment]
implemented

**Comment by propolisor** [comment]
400 WPM is pretty damn slow. I would suggest moving it up to 600. At 400 WPM the extension seems nearly worthless.

**Comment by jamestomasino** [comment]
You can change the speed to make it right for you by clicking the gear icon. See the demo video for an example. 

400 was chosen to be friendly to users new to RSVP.
