### ISSUE TITLE
Make the interface able to scroll with the webpage it's on and not scroll the user back up to the top of a webpage when activated

### ISSUE THREAD

**Issue by propolisor** [jamestomasino/stutter#11]
Whenever you activate the interface of the extension (that is, start "stuttering"), you are scrolled up to the top of the page where the RSVP presentational element sits. If you scroll down, it will not follow you but rather just stay in its static position. It should be able to scroll with the page and should appear at the top of the browser's viewport, not at the top of the document itself (which may be far far above anything the user is seeing at the moment), when activated.

**Comment by jamestomasino** [comment]
This will be handled as part of #13
