### ISSUE TITLE
Allow the user to configure the default size and location of the interface when activated

### ISSUE THREAD

**Issue by propolisor** [jamestomasino/stutter#12]
Because most webpages feature text in thin columns with whitespace on either side, I personally would like to position the RSVP interface not at the top of a webpage, but on the (right in my case) side, as a small (smaller than the default now) horizontal box, so that I can easily interact with both forms of the text at the same time. Other users might like to put it on the bottom or in the middle (which is where it should be closer to by default as people naturally look there when looking at their screens, not up at the top). Allowing the user to configure this themselves would be ideal.

As I mentioned in issue #11, the position of the interface should be relative to the browser's viewport, not the document itself, and should scroll with the document (that is, not change position or go off-screen because the user scrolled the document).

**Comment by jamestomasino** [comment]
You can now reposition the stutter bar on screen by dragging it with the drag-handler on the left side, above the options button. The plugin will remember this position for the future.

Added in v1.4.0
