### ISSUE TITLE
Put the RSVP interface closer to the middle of the screen by default

### ISSUE THREAD

**Issue by propolisor** [jamestomasino/stutter#13]
When looking at their monitors/screens, people's eyes tend to naturally comfortably rest toward looking at the middle of them, not the top. Looking at the top of them for extended periods of time, particularly if they're bigger screens, can be eye-straining.

I would assume that putting the interface at the top of the page instead of overlaid over the middle of the page is an attempt not to monopolize interaction with the page (though I don't see why as because the interface is statically placed in the document (as detailed in issue #11 of mine) any interaction with the page will either put the interface out of view or otherwise destroy your focus on it), which is an admirable goal.

As a mid-point between these two goals, I suggest that the interface be put half-way between the *bottom* of the page and the middle of the page, overlaid over the web page, by default. _(The reason I pick the bottom and not the top is because interaction with navigational/UI elements is more common at the top of webpages than at the bottom, meaning that putting the interface at the bottom is less likely to cover them up.)_

**Edit: Actually I changed my mind on the last italicized point for the following reason in another comment:**

>Actually, I change my suggestion about whether it should be placed towards the top or the bottom of the viewport. It should be placed more towards the top, as because text is read in almost languages from top to bottom, you want the RSVP interface to be in anticipation of the next main block of text you're going to be reading so that you can switch back and forth between both for meta-reading.

>So it should be replaced closer to the middle, far up enough that it doesn't crowd most of the text out, but far down enough that it doesn't block most webpage's navigational interfaces.

**Comment by jamestomasino** [comment]
You make a good argument for placement. I'll experiment with a static CSS layout (so it will scroll with you) and more central positioned layout. Pushing things to the top of the page was a bit of an automatic choice based on my prior Read plugin. The biggest battle in the styling is fighting against whatever the page defaults have set up for you. For instance, we don't know whether the page we're viewing is responsive or not, whether there is a static header or floating elements, forceful text styles, and so on. Stutter tries to avoid page style fighting as much as possible, but I think a static layout is still well within reach.

**Comment by propolisor** [comment]
Random idea: Perhaps the RSVP interface itself could have controls on it to move its location in the viewport dynamically in real time, with an icon that also binarily controls whether it covers up portions of its associated web page (is overlaid on it) or just steal spaces from it (both rendered adjacently)? Perhaps it could even just be a straight-up pop-up box so the user can just manipulate it/position it in whatever way they want with their own window manager? (Or, like the developer tools/inspector console in Firefox itself, it could have an icon that dynamically switches it between being its own window and being attached/docked to the tab it's in.)

**Comment by propolisor** [comment]
Actually, I change my suggestion about whether it should be placed towards the top or the bottom of the viewport. It should be placed more towards the top, as because text is read in almost languages from top to bottom, you want the RSVP interface to be in anticipation of the next main block of text you're going to be reading so that you can switch back and forth between both for meta-reading.

So it should be replaced closer to the middle, far up enough that it doesn't crowd most of the text out, but far down enough that it doesn't block most webpage's navigational interfaces.

**Comment by jamestomasino** [comment]
The pop-up idea is easy and I've seen some programs use it, but I never liked it myself. It pulls you out of your browser experience and it complicates things like mobile. Right now the plugin doesn't quite work on Firefox on Android, but it's close. Controls to move it around the screen will follow a centralized layout that is static.

There's some discussion in IRC about enhancing the settings panel with things like font size & color pickers to really let you customize the experience. I think this might be a better fit for that phase. I don't want to jump to that level until after I have browser-sync in place, though. I'd personally hate to go through all that customization only to have to do it again on my other computer.

Thanks for all the ideas, though!

**Comment by propolisor** [comment]
Here's my suggestion for a middle point between a completely customizable positioning system and something more rigid but still relatively flexible (though all within the browser's viewport and attached to the tabs, no individual windows):

By default, the interface would span the entire horizontal length of the viewport as you have it now, positioned by default slightly between the top of the screen and the middle (as I discussed in my prior comment, changed from my original position that it should be between the bottom and the middle).

Clicking and grabbing (or a mobile equivalent) the top or bottom of the interface would allow you to move the interface up or down (without resizing it), basically just moving it as a statically-sized bar up or down the screen (allowing you to reveal anything that is blocked by it), though flexibly/as a gradient and not by any particular distance (allowing you to position it exactly where you want it vertically).

On the edges of the "interface bar/block" would be two very thin buttons (like the classic arrows on scrollbars which mostly no longer exist) spanning the entire bar vertically (but very thin horizontally), with the one on the left featuring an arrow pointing left in the middle of it, and with the one on the right featuring an arrow pointing right in the middle of it.

When clicked, these buttons would compress the size of the interface horizontally (without affecting its vertical size) to 1/3rd of the viewport, positioned either attached/docked to the viewport's left edge or right edge (dependent on which button was clicked of course). The bar's vertical position would not be affected. This would allow my vision of being able to view the RSVP interface without it covering up any portion of the main text (so you can interact with both easily) on webpages that, as I mentioned previously, have white space on the sides of the page (which is most nowadays). (Whether you would want the RSVP front and center or off to the side I think would depend on how heavily you plan on relying on it to read that particular portion of text.) So, for example, if you're reading reddit, you can have the RSVP off to the right where the sidebar and whitespace below is while the comments are on the left, allowing you to see both. Or if you don't care about the main view at all and just plan on powering through all of the text on the page, you can have it front and center in front of everything.

Optionally, when the interface is docked to a side, its horizontal length can be manually adjusted in a similar fashion as its vertical position, except by manipulating the edge of the side that isn't docked. (So if it's docked to the right, you grab and move around the left edge of the box to control its overall horizontal length.) 

If the bar is docked to either side, clicking/tapping/grabbing it in the middle and dragging it back toward the middle will return to its default position of spanning the entire viewport again, with the vertical position unaffected. The extension will remember the exact positioning of your interface (on a per-domain basis would be really cool) between sessions/activations, activating it as it was before every time.

This would be relatively flexible while still being predictable and mobile-friendly, allowing for any use case of the extension that I can think of.

Also, thanks for the cool extension. Hopefully my ideas can be of some use to you.

**Comment by jamestomasino** [comment]
v1.3.0 fixes this and places the UI in the center of the screen, fixed as you scroll.
