### ISSUE TITLE
Some form of textual context?

### ISSUE THREAD

**Issue by propolisor** [jamestomasino/stutter#14]
So far when using this extension I've felt that while it does improve my "basic reading" speed, it does not improve my "meta-reading" speed as I can no longer make brief saccades toward further portions in the text to "strategize" (obviously on a wholly subconscious level) which portions I need to read very carefully word by word, which portions I can mostly skim over, which portions are in-between, etc. That is, overall it seems to slow down my reading of most texts (where I often give some paragraphs only very brief glances just to get the gist of them before moving on, only returning if the next paragraph after suggests that they were more important than I thought).

I've seen other implementations of the RSVP concept that print not only the main word you're supposed to be looking at highlighted in the usual fashion but also a bit of the further/prior portions of the text before and after it (with the exact length of these portions generally user configurable), usually in light-gray text so it's visible but doesn't stand out too much. This gives you a bit of context and enables some "meta-reading" strategies (which would enhance the utility of any playback controls you intend to add such as "pause", "play", "skip ahead a sentence", etc.).

**Comment by jamestomasino** [comment]
I don't think this is going to be in scope for stutter. If you want to use skimming it's best done before triggering stutter. Once you find something that interests you, select that paragraph and stutter it with the context menu.

Adding UI that requires your eyes to saccade during reading is counter to the goals of RSVP.
