### ISSUE TITLE
Suggestion for interactions between the RSVP interface and the actual text on the webpage

### ISSUE THREAD

**Issue by propolisor** [jamestomasino/stutter#15]
Because this idea is slightly more complex than my other issues, I will simply describe it in terms of the UX the user would have if my idea were implemented:

When the user either presses the "stutter" button to stutter all of the text on a webpage or highlights a particular portion of text and "stutters" it, they not only see the RSVP interface pop up, but the text they chose to be "stuttered" is highlighted on the page itself. (So if I stutter a paragraph that says "The quick brown fox jumps over the lazy dog. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.", not only does the RSVP interface pop up with "The" as its first word, but that actual paragraph of text is highlighted on the webpage outside of the RSVP interface.)

The current word of the text that the RSVP interface is running through is also highlighted on the webpage (more vibrantly and in a different color than the main text block as a whole), jumping from word to word as the RSVP continues. (So in my example, the word "The" in the actual paragraph on the webpage would be highlighted for a brief moment, before quickly jumping to "quick", then to "brown", etc., dependent on the WPM speed the user has set.)

If the word that would be highlighted next is outside of the browser's current viewport, the page automatically scrolls so that it's visible (without scrolling the RSVP interface off the page per issue #11). That is, the web page automatically scrolls so that no matter what word is being highlighted by the RSVP, it is also visible normally on the web page (synchronization between the RSVP view and the main browser view).

And my last idea, which I think is the coolest/most useful one, is that *the user is able to use the text block on the web page itself as a form of "playback control" for the RSVP*. That is, let's say I'm stuttering my example paragraph and the current word being displayed is "tempor". If I click on the word "amet" in the actual paragraph on the web page (that is, not in the RSVP interface), then the RSVP will go back to the word "amet" and continue from there, displaying "amet,", then "consectetur", etc. And I can use this to move the RSVP forwards, backwards, or to any point in the document, just by clicking on any part of it.

If the user pauses the RSVP and continues reading the document traditionally, the RSVP continuation point (the word it would start at if the user played the RSVP) will (optionally, user configurable) automatically scroll with the user's scrolling of the document, going down a line as the user scrolls down a line. (Again, this synchronizes the RSVP state and the traditional viewing state of the document, just in the context of the user reading the document traditionally for a bit). And, just like I can do when the document is playing, I can also change the location of the RSVP's next word just by clicking on the document while it's paused.

This would allow the user to easily switch back and forth between reading the document via RSVP or reading it traditionally without losing their place. It will also allow them to easily replay segments they didn't get all of. All they have to do is pause the RSVP (in the playback controls you mentioned adding), click back to where they started missing things on the actual document, and then hit play.

**Comment by jamestomasino** [comment]
I know exactly what you're talking about and it would indeed be very cool. Unfortunately there's no connection between the data being stuttered and the DOM on the page once begun. If you highlight text, right-click, then stutter it, the extension passes that data between the backend script and the front content script as a text string. There's security policy at play there.

If you click the icon to stutter, the entire page is being consumed with Mozilla's readability library before being textualized and stuttered. There's no connection from the text to the content on screen anymore. I don't see a reliable way to re-stitch them together.

That being said, I'll leave this issue open and marked as "Help Wanted". Maybe a better coder than me can make some progress.

**Comment by propolisor** [comment]
Considering this is a cool little extension, I knew that WebExtensions would just have to get in the way somehow.

**Comment by DaniloZZZ** [comment]
@jamestomasino Maybe include option of scrolling textview, below the RSVP, smth like this:
```
|      RSVPword       |
|---------------------|
| lorem ipsum dolor   |
| lorem ipsum dolor   |
| all the text goes here...
```
