### ISSUE TITLE
Suggestions for playback controls

### ISSUE THREAD

**Issue by propolisor** [jamestomasino/stutter#16]
Since you mentioned adding media player-style playback controls to the RSVP interface, I would like to suggest the following buttons:

Play/pause (obvious)

Rewind/Forward (would cause the text to play backwards instead of forwards, or return it to normal if it's already playing backwards, useful for rewinding to the exact point you want to resume at)

Fast forward (would increment playback speed by 100 WPM)

Slow down (would decrement playback speed by 100 WPM)

(Edit: Actually, thinking about it, this should be a slider where either end works as a button in the fashion I originally stated, like the volume controls in most media players.)

Brief skip forward (skips forward a whole sentence)

Brief skip back (skips back a whole sentence)

Big skip forward (skips forward a whole paragraph)

Big skip back (skip back a whole paragraph)

I would suggest the buttons be arranged in a horizontal row below the main interface in the following order: Slow down, fast forward, rewind/forward, pause/play, brief skip back, brief skip forward, big skip back, big skip forward

This puts the pause/play button (obviously the most used) in the middle, with the buttons I expected to be used most after it next to it.

**Comment by PhunkyBob** [comment]
I like this extension, but the major problem is the lack off playback controls.
Especially I would like to be able to slow down or accelerate with keyboard shortcuts.

**Comment by jamestomasino** [comment]
I would also enjoy being able to do some basic keyboard controls. Skip back x words, skip forward x words, pause/resume, and speed changes. I need to investigate which keypresses are safest to use in a browser contact. Since this extension runs on any page we don't want to conflict.

**Comment by jamestomasino** [comment]
I have a branch working with keybindings for the following:

- pause/play = enter key
- close stutter = escape key
- speed up wpm by 100 = alt+up arrow
- slow down wpm by 100 = alt+down arrow

I plan on adding a "skip ahead by x words" and "skip backwards x words" using alt+right and alt+left, but those will take a bit more work to accomplish.

**Comment by jamestomasino** [comment]
Okay, these keyboard bindings have been released with v1.7.0. You should get the update in your browser automatically. I'm not 100% satisfied with the experience of the alt-left/right and may tweak it more in the future. Right now it's skipping by 10 words at a time, but you can very quickly hit the key over and over to skip a greater distance.

I do appreciate that all this functionality comes without cluttering the UI. It's just a bit harder to discover. Maybe I'll add some help info on the options page.

Oh, and the browser window needs focus for any of the key bindings to work. That should be obvious, but if you click the Stutter icon to launch it, the window does not have focus right away. You need to click into it. I may be able to fix that, but I'm not sure.

**Comment by PhunkyBob** [comment]
Works fine for me.
Thank you!
