### ISSUE TITLE
When RSVPing a whole page, allow exclusion of presentational/navigational text (any text not in <p></p> blocks?)

### ISSUE THREAD

**Issue by propolisor** [jamestomasino/stutter#17]
I'm talking about text on a page like the text of "Reply", "Comment", "Delete", etc. buttons, form labels like "Name", "E-mail", etc. and other purely functional texts. Presumably people don't "read" this text so much as they do look at it, so RSVPing it is unnecessary. 

I think excluding any text not in <p></p> blocks would achieve this on most pages, though I am not sure. A brief visual indicator (like a small flash) between paragraph blocks to let you know that text has been excluded would be nice too (so that you can tell where one comment ends/begins on a forum for example).

**Comment by jamestomasino** [comment]
The full text page parsing is handled by Mozilla's readability library. Changes like that would be welcome, but they'll probably need to happen in that library and then get pulled in. The effort behind detecting real content and superfluous text decoration, comments, sidebars, etc, is extremely difficult. Their library is the best open source version I've found.

You can find a link to that project at the bottom of the README.
