### ISSUE TITLE
Doesn't work on Firefox for android

### ISSUE THREAD

**Issue by SevereOverfl0w** [jamestomasino/stutter#18]
When I click on stutter, nothing happens.

**Comment by jamestomasino** [comment]
That's correct. It's still on the todo list for Android. I can get things to install and events fire but the content script is not being injected. We'll get there soon, though.

**Comment by jamestomasino** [comment]
The reason this isn't working on Android is due to the "contextMenus" permission which allows you to select text and stutter it via a right-click context menu on desktop. That functionality does not exist on mobile. Rather than gracefully ignoring the permission, Firefox for Android fails to load the extension completely.

I can remove the small block using that feature and the rest of the plugin works (excepting some minor behavior with the drag code). I don't want to split the code-base and deploy a second plugin or remove the contextMenu from desktop. I'm exploring options.

**Comment by jamestomasino** [comment]
Firefox's Add-ons allows a very manual workaround which I'm using here. I have manually removed the contextMenu code and permission request from a specific manifest version. I submit that to the Mozilla Add-ons page as a unique version explicitly for Firefox for Android. Then I revert those changes, bump the version number, and submit the full version for desktop. It's cumbersome, but should work to get this working on mobile.

**Comment by jamestomasino** [comment]
It works, but it's pretty terrible.You need to go to the ["older versions" page](https://addons.mozilla.org/en-US/firefox/addon/stutter/versions/) and scroll down on your mobile device until you see a version that supports your platform (1.6.8 is the first). Then you can install it. I'll add a note to the readme.

**Comment by Stvad** [comment]
How do I actually install one of the old versions? When I go to the link above - the "add to firefox" is disabled and downloading and opening the extension file does not seem to do anything either

**Comment by jamestomasino** [comment]
I believe if you drag the downloaded `.xpi` file onto Firefox, it should install automatically.

**Comment by jamestomasino** [comment]
I should note, firefox for android support was added successfully, but then it was removed by Firefox itself when they updated to their new mobile version, removing support for 3rd party extensions completely. They're slowly adding approved add-ons back into the list, but I don't forsee Stutter being on that list anytime soon.

**Comment by Stvad** [comment]
> I believe if you drag the downloaded .xpi file onto Firefox, it should install automatically.

Uh, I don't think it's the kind of operation you can do on Android? 😅 

> firefox for android support
I see 🙁. 

there seems to be a clutch out there to make it work: https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/ (gonna try that now)

**Comment by Stvad** [comment]
huh, that actually worked. Managed to make it run on the FF Android!
![image](https://user-images.githubusercontent.com/81347/155909514-539efc77-59dd-4f88-9b16-ea47044b6ab7.png)
