### ISSUE TITLE
Firefox: Settings are essentially ignored...

### ISSUE THREAD

**Issue by Boydski** [jamestomasino/stutter#41]
I'm not even really sure how to describe this. Very frustrating.

I love the concept and would equally love to see this fixed.

The settings for when & where the engine pauses are utterly non-functional and nondeterministic. They quite simply don't work. Fresh, clean install of Firefox (even the dev version). The settings simply do not work.

I recommend a full audit & deep, objective, third-party QA.

**Comment by jamestomasino** [comment]
> The settings for when & where the engine pauses are utterly non-functional and nondeterministic

Can you describe the behavior you're seeing vs what you'd expect to see? I use Stutter daily in Firefox and haven't run into any problems with setting changes to any of the timing functions before.

**Comment by jamestomasino** [comment]
I'm guessing this issue is related to the 1-star review on the FF add-ons site. If so, here is my reply to that message:

Stutter has speed settings to support sentence ending punctuation (.,!?) distinctly from other punctuation. The other punctuation list includes: \/s,.…!¡‽:;‘’“”'’`><+=@&#~*^()[]{}<>«»·•¤¢$€£¥₩₪†‡°. The speed settings are multipliers, so if you want to delay longer than normal on punctuation, you'll need a number greater than 1.

If you have other punctuation that should be included I can do so.

**Comment by Boydski** [comment]
Hi James. Thanks for getting back with me.

I've gone as far as I can in UAT and some really deep debugging (from a user perspective) to find a pattern I could pass along. There just aren't any I'm able to define.

I've experimented with all the timeframe attributes you have in settings and they're almost entirely inert. At some point when items are all set to 3 or above, pauses are actually detected. But they're very, very much longer than the settings listed. I've disabled all other add-ons and have tested on multiple sites.

I see you dropped a new version recently. I'll take a look at the changes and see if I can make any sense of things.

**Comment by thiswillbeyourgithub** [comment]
I just installed stutter and am very very interested.

I think this is related to this issue : when I open the settings and change them, clicking on "save" instantly resets the page to the default value it seems.

**Comment by jamestomasino** [comment]
@thiswillbeyourgithub oh that does sound like a problem. Which browser & version are you using? Do you use the "sync" with it (ie, Firefox sync, or Chrome sync)? Which values did you change, and what did you change them to? The more info you can tell me the better I can try to recreate the issue.

Thanks!

**Comment by thiswillbeyourgithub** [comment]
firefox 72.0.1
on ubuntu 18.04
I use the sync feature.

I tried changing values one at a time but it behaves the same : it always visually resets the page (I don't know it the change is registered, but if I click twice it would be erased anyway). edit : wow I have been using stutter for the past hours and I don't get why but it seems to have resolved on its own ? Maybe somethings I did with some addons

**Comment by jamestomasino** [comment]
Hah, i'm glad to hear that, and glad to hear it fixed itself. If you disable localstorage, then it will disable the ability to save your setting changes. That may have been the issue for you. Technically I only use localstorage if sync storage isn't enabled, but I think the option disables both in tandem.

**Comment by jamestomasino** [comment]
Closing this issue for now. Perhaps it was related to the storage permission for the original poster as well, or perhaps it was fixed in an update. If the problem comes up again, let me know.
