### ISSUE TITLE
add a "start from here" button on right click

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#43]
Hi,
Currently there are two ways to use stutter :
1 - use the shortcut to read the whole page
2 - select a part of the text by dragging with the mouse then right click then stutter

I think it would be great to add a third way : right click then : "stutter from here to end".

edit : example of site where this would be already a bit useful : https://arstechnica.com/tech-policy/2020/01/apple-reportedly-nixed-plan-for-end-to-end-encryption-in-iphone-backups/
Using method 1 reads the text below each picture before getting to the main part. Method 2 takes loads of time and that's what we're trying to optimize here.

**Comment by jamestomasino** [comment]
This is pretty much the same request as #40 so I'm going to close this one, but thank you for the example. I'm still working on a good way to make this happen.
