### ISSUE TITLE
enhancement : add time estimation and wpm

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#44]
Hi !

A few more remarks : I think it would be nice to have displayed on the side : 
* current wpm
* total time spent reading the text
* remaining time

Thanks :)

**Comment by jamestomasino** [comment]
I added the progress bar highlighting a while back as a way to give a sense of completion. Having the times numeric seemed like it distracted the eye from the stuttering words, causing you to miss what was flashing by if you checked the time. Do you still think that's a valuable bit to add in?

As for the current WPM, I can probably add that by the gear icon in a faded-out color as an FYI.

**Comment by thiswillbeyourgithub** [comment]
Thanks for the quick reply (yayy timezones).

I was thinking of adding it gray on black to make it very subtle : you use it only if you need it otherwise you won't be distracted by it.

To give you an example. I'd like to read this and am genuinely curious as to how much time it would need : https://www.newyorker.com/culture/personal-history/my-brother-toms-schizophrenia

**Comment by jamestomasino** [comment]
okay, sounds good. I'll look to add time info and the current wpm as watermarks on the sides.

**Comment by jamestomasino** [comment]
This is done in v1.9.1 which was just published. It may take a few minutes for the add-on stores to update.

**Comment by jamestomasino** [comment]
@thiswillbeyourgithub btw-- https://ttm.sh/Ewi.png
