### ISSUE TITLE
adequate splitting of numbers

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#47]
Hello again again,

I was reading a french article containing number written the french way, for example : 156 000 081

It is currently being split as 156 then 000 then 081 which can both help reading but doesn't work for succession of 000, example : 382 000 000 829. The middle 000 are shown in succession and you can't see they're different.

May I suggest splitting long numbers according to the same logic as in #45 : long numbers should stay longer on screen but no be split.

Also, I don't know if you've thought about how to split numbers the american way : $192,402 <- the comma should not be interpreted as another word.

Just thought it might be useful to post this :) It's not like it's a big problem anyway.

**Comment by jamestomasino** [comment]
In looking deeper at the regex splitting rules I'm cleaning up some errors and working toward maintaining numbers as a single unit. I think I'm going to add a long-word exception if none of the characters are letters. I'm very close to a fix already, but having issues keeping % symbols on the ends of numbers.

**Comment by jamestomasino** [comment]
Well that was tricky, but I think my regular expression matching is a bit more robust for handling numbers, words with symbols, and very short (1 letter) period-separated words (e.g. a.m., p.m.). These all preserve into a single word. Numbers will not break for length either.

I still do split on spaces though. If French numbers are displayed that way, then I'd suggest we modify the wordRegex for the 'fr' locale.

This is what we have for English:

```regex
/([^\s/]+|[\r\n]+)/
```
We'll have to change that to have exceptions for spaces between numbers. I'll leave that out of this issue, though. I think that's deserving of a language specific issue if you'd like to start one.
