### ISSUE TITLE
reading stop abruptly

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#48]
Hi,

I have been having trouble with a specific site, here's an example

https://thecorrespondent.com/237/transnational-chat-why-do-we-still-need-the-news/29318872077-0f70db15?pk_campaign=newsletter-login&pk_medium=Daily&pk_source=mail

Open the page and stutter the whole page, it will stop at "completely". I think the rest of the text cotains an anchor to additionnal content on the side of the page or something. Either way, it's broken.

**Comment by jamestomasino** [comment]
It looks like the Mozilla readability library is having trouble parsing that page. If you click on "reader view" you'll see it's doing the same thing. I'm using the readability library to pre-parse the page for the core content when you click on the stutter icon. In this case, I think your best bet will be to highlight content and use the context menu to read the selection.
