### ISSUE TITLE
remarks on jumping backwards and forward in text

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#49]
Hi,

* Is it me or jumping is a bit laggy ? I think it lacks a visual cue when jumping has been triggered, especially backwards. I was thinking that maybe the part of the "scrollbar" that's been shortened or elongated should appear red (backward) or grey (forward) for 1 frame, indicating movement on the timeline. (Obviously I know nothing about UI)

* is it possible to edit in the settings how far the jump will go ? The current settings is not suited for all kinds of text and attention IMO

* what do you think about using the "slow start" after jumping backwards ?

**Comment by jamestomasino** [comment]
Ask and you shall receive:

- Seeking distance is configurable in the settings
- Seeking backwards triggers "slow start"
- Seeking in either direction will instantly update the screen, making it more noticable

1.9.5 released on FF. Chrome is still reviewing my last update, so it will take a little while longer to release.
