### ISSUE TITLE
Add optional support for "flankers"

### ISSUE THREAD

**Issue by jamestomasino** [jamestomasino/stutter#52]
There's some really interesting and promising data in [this study](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1469-8986.2010.01082.x) related to the inclusion of flankers in RSVP. Let's give that a shot as an optional feature which can be enabled/disabled. Directionality seems to have a major impact, so I'll look into whether it's better to have both words or only the following word flanking, and whether it should be styled the same as the target word or de-focused by color, transparency, or blur.

Comments welcome!

**Comment by thiswillbeyourgithub** [comment]
I was hesitating to ask for this :)

What do you mean by "directionnality" ?

I am eager to test this out. To be clear : we are talking about seeing the word in the middle and the preceding word just left of it as well as the following word being on the right. Right ?

If so this would give a sense of "scrolling" from right to left (the word on the right will then appear in the middle then on the left then never). At least if the place of the word stays the same (an issue that will arise when encountering words of different lengths).

To me it seems the best would be to keep the colors the same but to make the flankers more transparent (with of course the option to change the level in the settings ;) )

**Comment by jamestomasino** [comment]
Given the sample sentence, "The quick brown fox jumps over the lazy dog."  if the word currently being displayed is "fox", then the preceding flanker would be "brown" and the succeeding flanker would be "jumps". In a right to left language we would use a right to left flow so the logical words preceding and succeeding make sense, though their layout position would reverse.

I think I'm going to give an option to display either both the preceding and succeeding words, just the succeeding word, or neither. I need to take another closer look at the research, but it didn't look like showing only the preceeding word had any benefit.

I think a user controlable transparency setting makes sense as well. It would avoid me having to add another color to the palettes and retro all of them, and it would get me started in using CSS variables in the layout as well. Eventually I'll use that to allow for font customization as well.

**Comment by thiswillbeyourgithub** [comment]
I keep wondering about more flankers, but more transparent. Say 5 words :

The *brown* **fox** *jumps* over 

Fox is the read word, brown and jumps are quite transparent, the and over are even more transparent.

But i see a coding headache for the long or split words, they would impact the position of the flankers and thus the flow lf the scroll. How will you solve that ?

**Comment by jamestomasino** [comment]
Long overdue, but this is now being added in v1.10.0. In deeper reading on the subject it looks like the only statistically measurable improvement came with flankers to the right. I tested adding both and it looked awful, frankly. So this addition enables only the right-side flanker. It is available via a checkbox in the settings, but is disabled by default.

**Comment by jamestomasino** [comment]
Here's a demo video: https://www.youtube.com/watch?v=rI--n0zeVVY

**Comment by gwtnz** [comment]
I know I'm coming a bit late to the party here 😬 but do you still have the code for the options of before/after? I've used another RSVP app on mobile and found the before words helpful when it was moving just a tad too fast. Also an option to set the number of flanker words would be nice.

Another wishlist 😄 - ability to edit the theme colors? Looking to make a "Night mode" where the text is varying shades of red (easier for night vision) with maybe the highlight letter in white or some such (flankers in reds, brighter towards the central word).
