### ISSUE TITLE
Alt+Left and Alt+Right do not seem to work

### ISSUE THREAD

**Issue by OSHI7** [jamestomasino/stutter#57]
Hi,
I cannot jump back and foreward with these shortcut keys.
Firefox 74.0.1 (64-bit)

**Comment by OSHI7** [comment]
D'OH! Just figured this out. f.lux hijacked these keys or something. As soon as I terminated it, the jump keys work.  If I can only have one app..it's yours! you beat f.lux.
:)

**Comment by jamestomasino** [comment]
I've been a bit bogged down with work lately, but I do have a todo item to make the key bindings customizable. Once that drops you can play nicely with f.lux again! :) Thanks for your usage
