### ISSUE TITLE
Show text formatting

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [jamestomasino/stutter#59]
Hi,
In the same vein as #58, I think it would be cool if the titles of section were displayed as one line instead of word by word.

I think the major weakness in your app right now is that the rate at which words appear doesn't follow the logical structure of the text.

Let's take an example with a random link : https://en.wikipedia.org/wiki/Argumentation_theory

If you toggle reader view, you can see that the title are kept in the reader but your app doesn't treat them differently than text : 
![screenshot](https://user-images.githubusercontent.com/26625900/85117677-c0135480-b20e-11ea-9d49-7d89471b944e.png)

What I'm thinking is that when reaching a title, it should pause on it for some time while displaying the whole title. This would mark a pause between sections and help getting the point of what your reading.

I think we can't really keep up with a very high wpm speed for more than short bursts. So this should really help.

**Comment by jamestomasino** [comment]
This is another one that will be dependant on something related to #15 . I just don't have information on the DOM structure currently based on how we're pulling the screen data.
