### ISSUE TITLE
Break after em dashes

### ISSUE THREAD

**Issue by cole-miller** [jamestomasino/stutter#62]
The em dash `—` (U+2014) is used to mark several kinds of break between distinct thoughts in a sentence, or sometimes between sentences. It's often used without whitespace on either side, e.g. this paragraph (from [here](https://www.gutenberg.org/files/963/963-h/963-h.htm)):

> He had a certain air of being a handsome man—which he was not; and a certain air of being a well-bred man—which he was not. It was mere swagger and challenge; but in this particular, as in many others, blustering assertion goes for proof, half over the world.

Currently stutter doesn't recognize a word break when it sees an em dash, unless it's combined with whitespace, so `man—which` displays as one word ("manwich"?). I think it would be smoother if a break were made after the dash in this case, as with colons and semicolons. Ideally no break would be made just *before* the dash, whitespace notwithstanding, so it would group with the preceding word instead of standing alone, but that's not as important.

Since I'm noting a problem with stutter, I should add in balance that I really like it! RSVP is helpful for me since my instinct is to glance back a lot while reading, and this is definitely the best browser implementation I've found, so thanks for putting in the work on it.

**Comment by jamestomasino** [comment]
Hey @cole-miller !
Thanks for the issue log. I used to split on all dash-types. That turned out to be too much and I went the other way and allowed for hyphenated words. I totally get your justification for having an em dash as a breaking character, though. I'll make that happen! It's good timing as I have some security patching to do tonight anyway.

**Comment by jamestomasino** [comment]
This was updated and published in v1.9.11
