### ISSUE TITLE
Is it possible to darken the background whilst stutter is active?

### ISSUE THREAD

**Issue by gee-forr** [jamestomasino/stutter#73]
I love stutter, and use it to read through more long form articles, but I find that after I've read an article, I have a ghost-like after image burned into my eyes which takes a minute or two to go away, kinda like when your picture is taken with a strong flash.

The ghosting is effectively a negative image of the page with the stutter overlay, i.e. where stutter was, my eyes ghost that area lighter, and the rest of the page (normally white) is ghosted darker.

Would it be possible to have an option to dim the page in the background to closer match stutter's overlay so that this ghosting affect can be avoided by users with more sensitive retinas, like myself?

**Comment by jamestomasino** [comment]
What a cool idea! I'm going to explore this.

**Comment by jamestomasino** [comment]
This is being released in version v1.10.4 coming to a browser near you today. I've added a background screen that can be colorized by theme. I've added values to the existing themes. If you'd like to customize and add your own, check out the wiki.

**Comment by gee-forr** [comment]
OMG! This is amazing. Thank you so much!!!!

**Comment by gee-forr** [comment]
I've just updated and read something, it's exactly what I wanted. Thank you!
