### ISSUE TITLE
Have you ever tried to use on Firefox Android?

### ISSUE THREAD

**Issue by rodfersou** [jamestomasino/stutter#78]
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by jamestomasino** [comment]
Stutter worked well on the old firefox android. I was gravely disappointed in the disabling of add-on support when they released the new one. This is a good sign that is changing. I'll be sure to run through the steps and make sure we're still good to go for the future.

**Comment by jamestomasino** [comment]
[Demo video](https://vimeo.com/562126208) of v1.11.0 in Firefox Android Nightly

**Comment by rodfersou** [comment]
awesome! thanks!
