### ISSUE TITLE
Request: a progress bar, estimated reading times

### ISSUE THREAD

**Issue by jxyzn** [jamestomasino/stutter#83]
It would be nice to have a progress bar showing how far through the selected text range you've read. Perhaps also with estimated reading / remaining times?

**Comment by jxyzn** [comment]
Oh, I see some themes already have a progress bar of sorts. I'll close this.

**Comment by jamestomasino** [comment]
hi @jxyzn - the background of stutter is a giant progress bar. it changes color from left to right as you read. try different themes in the settings to see various color designs for it.

Also the right side of the bar has reading time estimates for your selection and speed.

Is there something in addition you want added?

**Comment by jxyzn** [comment]
In the default theme, the background progress bar doesn't show at all on my monitor, so as I was using it, I didn't think it had one. Switching themes shows me some that have visible progress indicators. The only minor thing left that I'd wanted to see was a countdown of remaining time.
