### ISSUE TITLE
Alt+left and Alt+right shortcuts are not working

### ISSUE THREAD

**Issue by ybrhue** [jamestomasino/stutter#86]
As mentioned in the title, those shortcuts are not working.
Using manjaro Linux with Plasma. I even disabled the system shortcuts for alt+left and alt+right, however they still don't work with stutter.

**Comment by jamestomasino** [comment]
Curses. I really need to get on with allowing customizations for keybindings.

**Comment by jamestomasino** [comment]
To be addressed by finishing #55

**Comment by jamestomasino** [comment]
This is now user-configurable in the settings panel. Updates being uploaded to add-on stores now.
