### ISSUE TITLE
Feature request: show more words

### ISSUE THREAD

**Issue by ybrhue** [jamestomasino/stutter#87]
It would be great, if you could also choose the amount of words that are shown.
If you are missing manpower to implement it, I could probably create a PR and code it, although I am not that familiar with js and typescript.

e.g.: using my sentence above and selecting a word option: 3
It would be
 great, if you
 could also choose
 the amount of
 words that are
 shown.

Kind regards
Yannick

**Comment by jamestomasino** [comment]
I've had this request a few times, but the academic research behind RSVP doesn't support it. I've added it to my "won't fix" list until I can find a study to support it. If it's something you're really into, please feel free to fork and give it a go. I would love to have somewhere to direct people who want that specific behavior.

**Comment by jamestomasino** [comment]
Absolutely! Open source rules.
