### ISSUE TITLE
Presenting letters instead of words

### ISSUE THREAD

**Issue by dgnorton** [jamestomasino/stutter#93]
When reading LWN articles, the text is presented one letter at a time rather than one word at a time. E.g., https://lwn.net/Articles/731581

![image](https://user-images.githubusercontent.com/209347/147575395-9555fc1a-1c31-4339-8d07-6e78bd9f7956.png)

![image](https://user-images.githubusercontent.com/209347/147575505-e8b2d027-591b-44dd-9b2e-a3c0b05bf378.png)

**Comment by jamestomasino** [comment]
That website has a strange stylesheet. They've styled "<span>" tags to have a white background. That's messing with color schemes as they display in Stutter so you can only make out the middle character, not the whole word.

I could modify the styles in Stutter to explicitly un-background spans, but I think that might be a slippery slope that will lead to messier CSS that's harder to maintain.

Normal rendering in Nord theme:
![Screenshot from 2021-12-28 14-26-14](https://user-images.githubusercontent.com/201422/147576227-0a8a3431-9903-4b2d-bace-ecd66b5b238a.png)

Disabling the style for SPAN background color:
![Screenshot from 2021-12-28 14-26-38](https://user-images.githubusercontent.com/201422/147576229-3695d2ac-f710-47d4-a4cc-682067486a42.png)

In the rare instance I run into something where the site styles interfere with Stutter I tend to copy/paste the whole page into a content-editable one, then stutter that, or I kick it into Wallabag (or Pocket) and Stutter that version.

**Comment by jamestomasino** [comment]
Thinking on this more, maybe I can add a stylesheet include that's a sort of "reset" but which forcefully sets the normal defaults rather than just those the browser screws up. I could then import it to `src-content/style.scss` and keep it isolated so it doesn't muddy up the main code.

**Comment by jamestomasino** [comment]
Huzzah! I found the lovely css property - `all: initial;`. Using this I'll have a fix for sites that screw up stutter's CSS launching momentarily.
